# Generated by Django 3.2.3 on 2021-05-24 18:19

import pgcrypto.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=250)),
                ('api_secret', pgcrypto.fields.CharPGPSymmetricKeyField(max_length=255)),
            ],
        ),
    ]
